### ISSUE TITLE
Data structures folder miss Linked-lists.

### ISSUE THREAD

**Issue by wassim31** [AbdeltwabMF/Anthology-of-Algorithms-and-Data-structures#1]
I would like to add Linked-lists data structure into the folder , also some functions to manipulate them like : 
Inserting ( at beginning , at a given position , at the end) 
Deleting a given node.
Reversing a linked list ( Iterative , recursive way ).
Happy to collaborate. :smiley:

**Comment by AbdeltwabMF** [comment]
I'm so happy to see your amazing implementation of linked list in my beloved language C. but unfortunately since this repository focus is on competitive programming and their data structures only and not on data structures in general i can not merge your pull request. and I do apologies for that. but once again i am so proud of you and you enthusiasm.

**Comment by wassim31** [comment]
Thanks for your encouragement sir , I loved your repository that's why I wanted to have an impact in this amazing work :smile: .
I wish you good luck sir , happy to see programmers like you in our Algerian community.
Please I have question : 
In competitive programming or interviews,  they don't ask a lot about linked lists ?

**Comment by AbdeltwabMF** [comment]
Linked list is a fundamental DS. but in competitive programming we often use an array or vector instead and that work just fine.
There are some online judges like leetcode and hackerrank ask for implementing such data structures. but the majority don't.
In interviews we expect that question for sure.
